### ISSUE TITLE
Improve naming

### ISSUE THREAD

**Issue by latvalam** [OpusCapita/fsm-workflow#1]
The current naming is not very descriptive. I suggest the following changes:

Machine -> **StateMachine** or **Workflow**
MachineDefinition -> **StateMachineDefinition** or **WorkflowDefinition**

machine.currentState({ object })  -> **getState**
machine.isFinal({ state }) -> **isFinalState**
machine.can({ object, event }) -> **canRaiseEvent**

These are trivial to accomplish with the other actions and therefore obsolete:

machine.is({ object, state})
machine.cannot({ object, event })

**Comment by asergeev-sc** [comment]
**Machine vs. Workflow** - I initially used **workflow** word but later I started to understand that it is better to use **machine** as I(we developing) Finite State Machine (FSM). *workflow* is just a synonym for state machine.
 
Also as from package/repository name description it is rather clear that we develop **Finite State Machine** but it is too verbose in the code to always have full name like "FiniteStateMachine". So I came down to simple name **Machine** (**machine**) which I consider is clear enough in the context of **fsm-<sub module>** package(s).

**machine.currentState** vs **machine. getState** - different FSM libraries has different names for such method like **current**, **getMachineState**, **state** and I believe existing function name **currentState** quite clearly tells developer/user what it does

**machine.isFinal({ state }) -> isFinalState**
Method was redeveloped from ```machine.isFinal({ state })``` is to more usable/convenient one ```machine.isInFinalState({ object })``` see #4 

**machine.can({ object, event }) -> canRaiseEvent**
**machine.is({ object, state})**
**machine.cannot({ object, event })**
As I explicitly mentioned in [readme file](/OpusCapita/fsm) I took as foundation the following library [fsm-as-promised](https://github.com/vstirbu/fsm-as-promised) e.g. some base API names are inherited from there.
