### ISSUE TITLE
getting error "machineDefinition is undefined" I already follow steps?

### ISSUE THREAD

**Issue by naveennsit** [OpusCapita/fsm-workflow#102]
I am using below package for demo application

https://www.npmjs.com/package/@opuscapita/fsm-workflow-core

I follow all steps whatever it is written in doc .But getting error 
**machineDefinition is undefined**

here is my code
https://codesandbox.io/s/inspiring-banzai-xumr2?file=/src/index.js

    var http = require("http");
    
    let { MachineDefinition, Machine } = require("@opuscapita/fsm-workflow-core");
    
    var machineDefinition = new MachineDefinition({
      schema: {
        initialState: "start",
        finalStates: ["finish"],
        transitions: [{ from: "start", event: "run", to: "finish" }]
      }
    });
    
    const object = { status: "none" };
    const machine = new Machine(machineDefinition);
    machine
      .start({ object })
      .then(({ object }) => {
        console.log(machine.currentState({ object }));
        // start
        return machine.sendEvent({ object, event: "start" });
      })
      .then(({ object }) => {
        console.log(machine.currentState({ object }));
        // finish
      });
    
    //create a server object:
    http
      .createServer(function(req, res) {
        res.write("Hello World!"); //write a response to the client
        res.end(); //end the response
      })
      .listen(8080); //the server object listens on port 8080

could you please tell me where I am doing wrong .? 

One more thing this package is `Apache-2.0` licence .can I use this package in my real project ?

**Comment by estambakio-sc** [comment]
Hi @naveennsit 

Actual API for `machine` is the following:

```
const machine = new Machine({ machineDefinition }); // notice it's inside curly braces
```

About license: yes, it's fine. For example most of Java open source libraries use the same license.

**Comment by naveennsit** [comment]
@estambakio-sc   still not working getting error now


```
[/Users/b0207296/WebstormProjects/node/service-a/node_modules/@opuscapita/fsm-workflow-core/lib/Machine.js:62
      throw new Error("'convertObjectToReference' is not defined\nIt is expected to be a function like this:\nfunction(object) {\nreturn {\nbusinessObjType: ...   // business object type/class (examples: 'invoice', 'supplier', 'purchase-order')\nbusinessObjId: ...     // business object unique id (examples: '123456789')\n}\n}\n    ");
      ^

Error: 'convertObjectToReference' is not defined
It is expected to be a function like this:
function(object) {
return {](url)

```

here is my updated code


```
var http = require("http");

let { MachineDefinition, Machine } = require("@opuscapita/fsm-workflow-core");

var machineDefinition = new MachineDefinition({
  schema: {
    initialState: "start",
    finalStates: ["finish"],
    transitions: [{ from: "start", event: "run", to: "finish" }]
  }
});

const object = { status: "none" };
const machine = new Machine({ machineDefinition });
machine
  .start({ object })
  .then(({ object }) => {
    console.log(machine.currentState({ object }));
    // start
    return machine.sendEvent({ object, event: "start" });
  })
  .then(({ object }) => {
    console.log(machine.currentState({ object }));
    // finish
  });
//create a server object:
http
  .createServer(function(req, res) {
    res.write("Hello World!"); //write a response to the client
    res.end(); //end the response
  })
  .listen(8080); //the server object listens on port 8080
```

**Comment by estambakio-sc** [comment]
Yeah looks like README was not updated in time :) 

Have a look at what's missing in `complete example`: https://github.com/OpusCapita/fsm-workflow/blob/master/packages/examples/complete-demo/src/server/fsm/fsm.js#L22-L25

BTW `history` prop is **not** mandatory.

**Comment by naveennsit** [comment]
ok I will try and update you

**Comment by naveennsit** [comment]
@estambakio-sc  i tried but will 50% working ..!! not sure where I am doing wrong..

```
let { MachineDefinition, Machine } = require("@opuscapita/fsm-workflow-core");

var machineDefinition = new MachineDefinition({
  schema: {
    initialState: "start",
    finalStates: ["finish"],
    transitions: [{ from: "start", event: "run", to: "finish" }]
  }
});

const object = { status: "none" };
const machine = new Machine({ machineDefinition ,
    convertObjectToReference: object => ({
      businessObjType: 'invoice',
      businessObjId: 'invoiceNo'
    }),}
  );
machine
  .start({ object })
  .then(({ object }) => {
    console.log(machine.currentState({ object }));
    // start
    return machine.sendEvent({ object, event: "start" });
  })
  .then(({ object }) => {
    console.log(machine.currentState({ object }));
    // finish
  });
```


I am not sure what it to write in this  object.I write the same thing whatever it is written in complete demo

```
 businessObjType: 'invoice',
      businessObjId: 'invoiceNo'
```

after running above code I am getting this on console

```
LTB0207296-Mac:service-a b0207296$ node test
start
(node:14737) UnhandledPromiseRejectionWarning: #<Object>
(node:14737) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 2)
(node:14737) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.


```

**Comment by naveennsit** [comment]
expected output should be `start` and then `finish`

**Comment by estambakio-sc** [comment]
You defined event "run" but you send non-existing "start" `machine.sendEvent({ object, event: "start" }) <- "start", but should be "run"`

BTW if you add `.catch` there should be a readable error for such case.

About `convertObjectToReference` (important if you use `history` package): 
- `businessObjType` can be anything which defines a type of object you pass around
- `businessObjId` is a name of property in your object which uniquely identifies your object. If you use `history` then you can find what happened with this type of objects and with this particular object, which events occurred with it etc.

**Comment by naveennsit** [comment]
great package ..!! thanks for help.!!! last comment again same question can I use this package for my company project ??? because this is not `MIT` license.it is `APACHE 2` license. ??

**Comment by naveennsit** [comment]
one last query have you ever used any `rule engine` package in node js . so that business can defined there rules like in `xls` file and  node js will read that rules (seperate from code for good practice) same as you do in workflow

**Comment by estambakio-sc** [comment]
> one last query have you ever used any `rule engine` package in node js . so that business can defined there rules like in `xls` file and node js will read that rules (seperate from code for good practice) same as you do in workflow

I don't think I understand what you mean. Can you elaborate?

**Comment by naveennsit** [comment]
ok. I will explain more.let take example we have multiple microservices in our project.There is a one `task-service` it duty is to assign the task to `engineers`. There is criteria or rules  to assign the  task to a `engineer`, example task given  to engineer `1` priority those age is between 25 to 30. `2` priority to those whose age is greater than 30. Mostly we are using `priority queue ` `data structure `. so In java there are `inbuild` package  `drool`


https://www.baeldung.com/drools-excel

see link
in xls sheet rules are defined and it is separate from code.secontly if we change the rules assigment of tasks is changed

is there any package available in nodejs where we defined our rules

**Comment by naveennsit** [comment]
any idea ??

**Comment by estambakio-sc** [comment]
No, I've not used something similar. You'll need to find it yourself.
