### ISSUE TITLE
Update deprecated import-function

### ISSUE THREAD

**Issue by jluukka-ge** [OpusCapita/fsm-workflow#104]
Meta-Info | Value
-- | --
ExtProjectId | ???
Original Estimation | ???h
Remaining Estimation | ???h

The `sequelize.import` -function has been deprecated and it is recommended to simply use `require` instead. See deprecation notice here:  https://sequelize.org/master/manual/models-definition.html .

A call to `sequelize.import` can be found in `packages/history/src/models/definitions/index.js`. This prevents us from migrating to the latest version of Sequelize until the deprecated function is replaced.

Therefore, the task is to replace the deprecated function with a working solution.

**Comment by estambakio-sc** [comment]
Implemented in #105
