### ISSUE TITLE
Change current arrows

### ISSUE THREAD

**Issue by abaliunov-sc** [OpusCapita/fsm-workflow#22]
Change current arrows to arrows like Normal Sequence Flow in BPMN 2.0
![image](https://user-images.githubusercontent.com/28590602/34265144-25aa058e-e686-11e7-9e09-88adf1ded037.png)
See [Normal Sequence Flow In Bpmn](http://www.conceptdraw.com/diagram/normal-sequence-flow-in-bpmn)

**Comment by asergeev-sc** [comment]
Ticket is not actual for the moment
