### ISSUE TITLE
Create workflow (CRUD) editor

### ISSUE THREAD

**Issue by estambakio-sc** [OpusCapita/fsm-workflow#23]
Goal: create a simple schema editor (React component) which has a built-in editable JSON [schema](https://github.com/OpusCapita/fsm-workflow/tree/master/core) where a user can define: 

1. fsm schema name - input field,
2. initial state - a dropdown input,
3. final state(s) - multiselect input,
4. transitions - create, edit and delete functionality.

Names of states are parsed from `transitions` object. User cannot just add a state if there is no corresponding transition which mentions this state.

Button `add transition` or `create` opens up a modal dialog with a form, where user can 

- select existing `from` and `to` states or enter a new state name
- enter a name of `event`
- click `Ok` to close the modal

The component should emit new schema `onChange` (if schema is valid).

**Comment by estambakio-sc** [comment]
[Current demo](https://opuscapita.github.io/fsm-workflow/branches/issue-23(slash)workflow-editor/crud-editor/?currentComponentName=WorkflowEditor&maxContainerWidth=100%25&showSidebar=false)

**Comment by amourzenkov-sc** [comment]
Package [viz.js](https://github.com/mdaines/viz.js) can be use for FSM directed graph auto-building and visualization.  See [an example](http://www.webgraphviz.com/) which works in IE 11 also.

A converter from our state machine configuration to the .dot language expected by [GraphViz](http://www.graphviz.org/) can be written similar to [this package](https://github.com/jakesgordon/javascript-state-machine/blob/master/docs/visualization.md).

**Comment by estambakio-sc** [comment]
[Current demo](https://opuscapita.github.io/fsm-workflow/branches/issue-23(slash)workflow-editor/crud-editor/?currentComponentName=WorkflowEditor&maxContainerWidth=100%25)

States and transitions are implemented as independently editable within own editors.

TODO: 

1. confirmation dialog for
  - leaving without saving changes (guards and states)
  - if transitions will be deleted when a used state is deleted (and/or maybe give a chance to replace all occurencies of deleted state with one of existing states)
2. visible and readable errors in case of trying to create existing state
3. Pass css colors via props

**Comment by estambakio-sc** [comment]
Notes for reference

![img-0290](https://user-images.githubusercontent.com/31243790/35555503-6e9297f4-05b0-11e8-882b-fafb134b0b18.JPG)

![img-0291](https://user-images.githubusercontent.com/31243790/35555512-72adaea0-05b0-11e8-9a19-643e1987b4a7.JPG)

**Comment by estambakio-sc** [comment]
For future reference: (possibly better) solution for workflow visualization: [mxGraph](https://github.com/jgraph/mxgraph)

example: [full editor](https://jgraph.github.io/mxgraph/javascript/examples/grapheditor/www/index.html), [simpler editor](https://jgraph.github.io/mxgraph/javascript/examples/editors/workfloweditor.html)

docs: [one](https://jgraph.github.io/mxgraph/docs/manual.html#2.2.1), [two](https://jgraph.github.io/mxgraph/javascript/index.html)

Upsides: 90 degree arrows, names for vertexes and arrows, drag&drop editor. 

Challenges: it's a big one and could take quite some time to get comfortable with.

**Comment by estambakio-sc** [comment]
[Current demo](https://opuscapita.github.io/fsm-workflow/branches/issue-23(slash)workflow-editor/editor/?currentComponentName=WorkflowEditor&maxContainerWidth=100%25) after renaming directory.

**Comment by estambakio-sc** [comment]
Implemented, merged into `master` in #42

Current demo: [link](https://opuscapita.github.io/fsm-workflow/branches/master/editor/)
