### ISSUE TITLE
Implement workflow visualization for "crud-editor" using "graphviz"

### ISSUE THREAD

**Issue by kvolkovich-sc** [OpusCapita/fsm-workflow#25]
**Current crud-editor appearance:**

![screen shot 2018-01-24 at 10 51 09 am](https://user-images.githubusercontent.com/24652543/35320403-bbf3d550-00f4-11e8-80b4-ec76bb7d323e.png)

**Required changes:**

* Rename `Updated schema` => `Schema`
* Place `graphvis` visualization in a row with json schema definition

  `graphviz` visualization example: http://www.webgraphviz.com/

* Improve visualization styles for a better look'n'feel

**Comment by kvolkovich-sc** [comment]
[Current demo](https://opuscapita.github.io/fsm-workflow/branches/issue-25(slash)workflow-visualization/crud-editor/?currentComponentName=WorkflowEditor&maxContainerWidth=100%25)

**Comment by kvolkovich-sc** [comment]
Wontfix cause new workflow editor UI implementation started: https://github.com/OpusCapita/fsm-workflow/issues/23

**Comment by nstoliar-sc** [comment]
Tested.
1. If workflow has a lot of branches, workflow schema is not placed in visualization area.
![112_cutting_of_blocks.png](https://images.zenhubusercontent.com/5a2929dc8a75884b908a3a71/de482cc6-846d-429a-b80b-2692d97b46e4)

2. If user inputs very long name of some block, inputting field climbs on neighbor elements of page.
![114_field_climbing.png](https://images.zenhubusercontent.com/5a2929dc8a75884b908a3a71/3eabf359-264e-4a18-a1d9-d20d19fb948f)

3. Legend of schema climbs on vertical scroll when workflow has a lot of branches.
![113_climbing_on_scroll.png](https://images.zenhubusercontent.com/5a2929dc8a75884b908a3a71/3ce9f99d-0be4-4aaa-9916-b33f769293da)

4. If workflow is very long, it is not placed in in visualization area in Firefox browser. 
![111_long_schema.png](https://images.zenhubusercontent.com/5a2929dc8a75884b908a3a71/6adb0d78-a5ad-4d9c-b3e2-8f03aabe040f)

Spent 2.5 hours.
