### ISSUE TITLE
Add support for supplying a path expression instead of value to params editor inputs

### ISSUE THREAD

**Issue by estambakio-sc** [OpusCapita/fsm-workflow#52]
Currently [here](https://opuscapita-fsm-workflow-demo-master.azurewebsites.net/editor) (transitions -> 1st -> actions -> 1st -> edit)  we can see regular editor for parameters, same both for actions and guards. It is needed to add a possibility to not only assign a constant value to a param, but also give it a path expression value, so that in future value could be taken at runtime from business object via this path expression.

**Comment by estambakio-sc** [comment]
[Current demo](https://opuscapita-fsm-workflow-demo-issue-52-path-expression.azurewebsites.net/editor) (transition -> actions -> action editor or transitions -> guards -> guard editor)

**Comment by estambakio-sc** [comment]
[Demo website](https://opuscapita-fsm-workflow-demo-issue-52-path-expression.azurewebsites.net/editor)

Things to test: `editor`, parameters editor in particular (guard -> edit and action -> edit).

**Comment by nstoliar-sc** [comment]
1. If user inputs date manually in 'Date Of Birth' or 'Important Dates' of 'Action invocation' page, previous on one day date is set. For example: user inputs '01/01/2018', but '31/12/2017' is set.
2. Always last value is deleted from numeric multi value lists ('Next Lottery Numbers' and 'Montly Interest History') on 'Action invocation' page, if user deletes some value.
3. Calendar can be partially hidden on 'Action invocation' page if it added in bottom part of window. 
![137](https://user-images.githubusercontent.com/25082017/37099301-fd639824-2230-11e8-9ec1-02d2366f31ce.png)

4. Orthographic mistake in 'Monthly' word in 'Monthly Interest History' on 'Action invocation' page: absent 'h' symbol.
![138](https://user-images.githubusercontent.com/25082017/37099311-039bc428-2231-11e8-9497-d778de9f3468.png)

5. If user opens 'Action invocation' page, doesn't make any changes and then close this page, warning message about unsaved date appears.
6. 'Some Array' field is not displayed for 'Update Processed By' action on 'Action invocation' page. 
7. User can save empty value for 'Restricted Roles' field in 'Edit guard' page. 
8. If user inputs value 'invoice["invoiceNo"] = 1<2' in 'Expression' tab of 'Edit guard' page, for all objects value 'true' is assigned.
9. If user adds value in 'Expression' tab of 'Edit guard' page using 'Example object', cursor is set in start of expression field. 
10.  If user opens 'Edit guard' page on 'Predefined function' tab, doesn't make any changes and then close this page, warning message about unsaved date appears.

Spent 5 hours.

**Comment by estambakio-sc** [comment]
1. fixed
2. fixed
3. wontfix
4. fixed
5. fixed
6. irrelevant
7. wontfix (test case, it doesn't matter)
8. fixed
9. fixed (cursor is set to the end of inserted expression)
10. fixed

Please review changes @nstoliar-sc 

[Demo website](https://opuscapita-fsm-workflow-demo-issue-52-path-expression.azurewebsites.net/editor)

**Comment by nstoliar-sc** [comment]
1. If user create or edit some new action and than opens it again, doesn't make any changes and then close this page, warning message about unsaved date appears.
2. If user adds value in 'Expression' tab of 'Edit guard' page using 'Example object', cursor is still set in start of expression field.
3. If user create or edit some guard and than opens it again on 'Predefined function' tab, doesn't make any changes and then close this page, warning message about unsaved date appears.
Spent 2 hours.

**Comment by estambakio-sc** [comment]
@nstoliar-sc  1, 2, 3 fixed.

Please confirm.

**Comment by nstoliar-sc** [comment]
If user deletes some action or guard, message "Do you really want to remove this guard/action?" is shown. If user confirm deleting and then clicks on "close" button (close without saving) on action or guard pop-up, message "Do you really want to remove this guard/action?" is shown again. If user click on "Ok" button, pop-up is closed, but deleted guard/action stays. It is seemly, necessary to show "You have made changes. Closing this editor will lose these changes." in that case. Spent 2 hours.

**Comment by estambakio-sc** [comment]
@nstoliar-sc fixed, check again please.

**Comment by nstoliar-sc** [comment]
Tested. Please, merge with master branch. Spent 0.5 hour.
