### ISSUE TITLE
Event-based hooks

### ISSUE THREAD

**Issue by dzhitomirsky-sc** [OpusCapita/fsm-workflow#6]
*Intro*
When we send an event or start workflow for an object we might need an ability to react dynamically  on successful/failed transition.

*Proposal*
Lets use event base approach - when the transition is finished we can fire an event according to the result. The developer that uses the _fsm_ can subscribe to the event in any place of the application.

*Technical proposal*
Node js provides [built-in pub-sub mechanism](https://nodejs.org/dist/latest-v6.x/docs/api/events.html), but the browser doesn't. If we want to stay platform-independent , we can use the same approach as for _Promises_: use build it Event emitter by default and provide ability to use custom event-emitter if default one in not available.

**Comment by kvolkovich-sc** [comment]
Maybe look at: https://github.com/asyncly/EventEmitter2
It is an browser-compatible reimplementation of the Node.js EventEmitter module.

**Comment by asergeev-sc** [comment]
I believe described feature fits end application not the library. You can implement attach your/existing event queue to the transition execution exit points.
