### ISSUE TITLE
Add support for `negate` property

### ISSUE THREAD

**Issue by estambakio-sc** [OpusCapita/fsm-workflow#63]
TODO:

- [x] (implemented in #65) In core: restrict `negate` property only for function-style guards and automatics, don't use for expressions.
- [x] (implemented in #66) In editors: add `negate` switcher inside guard/automatic editors.

**Comment by estambakio-sc** [comment]
[Demo link](http://opuscapita-fsm-workflow-demo-issue-63editor-negate.azurewebsites.net/editor)

Things to test: 
- transitions -> automatic (new thing)
- transitions -> automatic -> negate
- transitions -> guards -> negate

**Comment by nstoliar-sc** [comment]
Tested. "Negate" check boxes were added for Guards and Automatics. "Always automatic" check box was added for Automatics. If some changes are made for this check boxes and user closes pop-up, message about unsaved data appears. Please, merge with master branch. Spent 1 hour.
