### ISSUE TITLE
Make editor able to handle empty schema, aka create new transition

### ISSUE THREAD

**Issue by estambakio-sc** [OpusCapita/fsm-workflow#67]
Also add `download schema` button.

**Comment by estambakio-sc** [comment]
[Complete demo](http://opuscapita-fsm-workflow-demo-issue-67allow-empty-schema.azurewebsites.net/editor)

[Editor demo](https://opuscapita.github.io/fsm-workflow/branches/issue-67-allow-empty-schema/editor/index.html?currentComponentName=WorkflowEditor&maxContainerWidth=100%25)

**Comment by nstoliar-sc** [comment]
Tested. json schema file is downloaded correctly in Chrome, IE and FF. Please, merge with master branch. Spent 0.5 hour.
