### ISSUE TITLE
Let application restrict states available in workflow editor

### ISSUE THREAD

**Issue by estambakio-sc** [OpusCapita/fsm-workflow#74]
Meta-Info | Value
-- | --
ExtProjectId | JCPROC-01
Original Estimation | 4h
Remaining Estimation | 0h

https://github.com/OpusCapita/minsk-core-externals/issues/104

### TODO
- [x] Add `stateConfig` prop for `fsm-workflow-editor`:
```
stateConfig={{
  availableNames={['state1', 'state2', ...]}
}}
```
- [x] when user adds a state, restrict available state names to `stateConfig.availableNames` (`select` instead of text input)

If `stateConfig.availableNames` is not supplied - preserve current behavior.

**Comment by estambakio-sc** [comment]
[Demo link](https://opuscapita.github.io/fsm-workflow/branches/issue-74/editor/?currentComponentName=WorkflowEditor&maxContainerWidth=100%25)

**Comment by nstoliar-sc** [comment]
Tested. Stage is removed from list after adding this stage to buisiness-process. It is impossible to add more one same stage. If stateConfig.availableNames is not supplied, text input is available for inputting names of stages. Please, merge with master branch. Spent 1.5 hours.
