### ISSUE TITLE
Workflow editor doesn't show full chart

### ISSUE THREAD

**Issue by apechenko-sc** [OpusCapita/fsm-workflow#78]
Meta-Info | Value
-- | --
ExtProjectId | JCCMMN-01
Original Estimation | ???h
Remaining Estimation | ???h

![simworkflow](https://user-images.githubusercontent.com/24652264/44386262-b2191d80-a52a-11e8-8c8c-8bc38e680493.png)

Sample schema to reproduce the problem
[schema.zip](https://github.com/OpusCapita/fsm-workflow/files/2305191/schema.zip)

**Comment by estambakio-sc** [comment]
[Demo](https://opuscapita.github.io/fsm-workflow/branches/master/editor/?currentComponentName=WorkflowEditor&maxContainerWidth=100%25)
