### ISSUE TITLE
Add support for i18n in workflow editor

### ISSUE THREAD

**Issue by apechenko-sc** [OpusCapita/fsm-workflow#81]
Meta-Info | Value
-- | --
ExtProjectId | JCINV-01
Original Estimation | 8h
Remaining Estimation | 0h

All UI elements including names of guards, states, events, actions and their params must be translatable.

**Comment by estambakio-sc** [comment]
Please provide translations based on this file https://github.com/OpusCapita/fsm-workflow/blob/issue-81/packages/editor/src/i18n/en.js :

- [x] `de` @nhryhoryeva-sc 
- [x] `ru`, `fi`, `no`, `sv` @amotuz-sc

**Comment by estambakio-sc** [comment]
Demo link https://opuscapita.github.io/fsm-workflow/branches/issue-81/editor/?currentComponentName=WorkflowEditor&maxContainerWidth=100%25

Translated: `en`, `de`

What to test: 
- all UI parts (buttons, etc) are translated
- some schema-related parts are translated (actions `testAction`, `sendMail`, condition (guard/automatic) `userHasRoles`, states `approved`, `inspectionRequired`)

**Comment by dshwedovsky-sc** [comment]
UI: labels, messages, modals, states are translated to German and English
