### ISSUE TITLE
Zero values in numeric inputs considered empty

### ISSUE THREAD

**Issue by estambakio-sc** [OpusCapita/fsm-workflow#83]
Meta-Info | Value
-- | --
ExtProjectId | JCINV-01
Original Estimation | 1h
Remaining Estimation | 0h

**How to reproduce:**
Transitions -> [first row] Actions -> [first action] Edit -> insert `0` into a numeric input (either `integer` or `decimal`, these are `Age` and `Bank Account Balance` on demo installation). Hit `Save`. Now return to editor for this action - those numeric inputs are empty.

![fsm-workflow-editor-state-editor-zero-bug](https://user-images.githubusercontent.com/31243790/46347857-ad7d7400-c655-11e8-95dd-90354db731d9.gif)

**Expected behavior:** 
Zero number is a valid value for input, it should be in there.

**Comment by estambakio-sc** [comment]
Demo https://opuscapita.github.io/fsm-workflow/branches/issue-83/editor/

![fsm-workflow-editor-state-editor-zero-bug-fixed](https://user-images.githubusercontent.com/31243790/46348549-fdf5d100-c657-11e8-8df3-533671bc7eeb.gif)

**Comment by dshwedovsky-sc** [comment]
Checked on [installation](https://opuscapita.github.io/fsm-workflow/branches/issue-83/editor/)
Impossible to save Date value in some action

**Comment by estambakio-sc** [comment]
Fixed, please check.

**Comment by dshwedovsky-sc** [comment]
Checked on [installation](https://opuscapita.github.io/fsm-workflow/branches/issue-83/editor/)
In is possible to set any value into action of different types.
0 value also saved
